### ISSUE TITLE
visit counter db row not append after day 2

### ISSUE THREAD

**Issue by juicycool92** [juicycool92/blogProjectForjellojay#3]
have to solve issue b4 1.0

**Comment by juicycool92** [comment]
fixed at counterModule.js
hopefully works by now

**Comment by juicycool92** [comment]
C:\Users\Jay\Documents\GitHub\blogProjectForjellojay\modules\counterModule.js:32
                        if(err || !res.rows[0].visitcount){
                                              ^

TypeError: Cannot read property 'visitcount' of undefined
    at Query.client.query (C:\Users\Jay\Documents\GitHub\blogProjectForjellojay\modules\counterModule.js:32:26)
    at Query.handleReadyForQuery (C:\Users\Jay\Documents\GitHub\blogProjectForjellojay\node_modules\pg\lib\query.js:126:10)
    at Connection.<anonymous> (C:\Users\Jay\Documents\GitHub\blogProjectForjellojay\node_modules\pg\lib\client.js:163:19)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (C:\Users\Jay\Documents\GitHub\blogProjectForjellojay\node_modules\pg\lib\connection.js:117:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

**Comment by juicycool92** [comment]
in count module line 32
if(err || !res.rows[0].visitcount){

changed to 
if(err || !res.rows[0]){

common mistake, counter is now counting only per day
